---
title: "p8105_hw2_KJW2175"
author: "Kennedy Wade"
date: "2025-09-26"
output: github_document
---

##Problem 1

1. Cleaning the csv
2. Breaking up, removing and replacing variables

```{r}

library(tidyverse)
library(janitor)

pols_df = 
    read_csv("./hw2data/pols-month.csv", na = c("NA", ".", "")) |>
    janitor::clean_names(pols_df)
    separate(col = mon, 
    into = c("year", "month", "day"), 
    sep = "-"
  ) |>
    mutate(mon = case_match(
      mon, 
      "01" ~ January, 
      "02" ~ February,
      "03" ~ March,
      "04" ~ April,
      "05" ~ May,
      "06" ~ June,
      "07" ~ July,
      "08" ~ August, 
      "09" ~ September
      "10" ~ October
      
      
      
    )

```

```{r}
pols_df = 
  separate(col = mon, 
    into = c("year", "month", "day"), 
    sep = "-"
  )

```

```{r}
 pols_df =  
  mutate(
    month = month.name[month],                       
  president = ifelse(prez_gop == 1, "gop", "dem")  
```

```{r}
pols_df =  
  select(-prez_dem, -prez_gop, -day)
```




